FROM php:8.2-cli-alpine

RUN apk add --no-cache \
    git \
    unzip \
    libpq-dev \
    oniguruma-dev \
    curl

RUN docker-php-ext-install pdo pdo_pgsql mbstring

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/app

COPY . .

RUN composer install --no-interaction --no-dev --prefer-dist

CMD ["php", "-S", "0.0.0.0:8000", "-t", "public"]
